[theme]
primaryColor = "#1e3799"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2f3542"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
